### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ProcessException: No such file or directory

### ISSUE THREAD

**Issue by blockshark** [amin-ahmadi-com/flython#1]
I have received the following error, may I ask what the problem is?
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ProcessException: No such file or directory
  Command: python ./main.py --uuid 1a6dfea8-edf1-48e2-99ab-8d4823604937
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      Flython._initializeUnprotected (package:flython/flython.dart:98)
#3      Flython.initialize.<anonymous closure> (package:flython/flython.dart:86)
#4      Mutex.protect (package:mutex/src/mutex.dart:79)
<asynchronous suspension>
#5      Flython.initialize (package:flython/flython.dart:85)
<asynchronous suspension>
<asynchronous suspension>

**Comment by blockshark** [comment]
Mac OS
